--- #YAML:1.0
name:                String-Truncate
version:             0.101
abstract:            a module for when strings are too long to be displayed in...
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Sub::Exporter:                 0.953
    Sub::Install:                  0.03
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo Signes <rjbs@cpan.org>
